# Generated by Django 5.1.3 on 2024-11-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Amenities',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='available_rooms_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_rules',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
