# Generated by Django 5.1.3 on 2024-11-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_hotel_amenities_hotel_available_rooms_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='available_rooms_count',
            new_name='delux_rooms_count',
        ),
        migrations.AddField(
            model_name='hotel',
            name='semidelux_room_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
